### ISSUE TITLE
OAR job not scheduled

### ISSUE THREAD

**Issue by Nivekiba** [pmorillon/terraform-provider-grid5000#16]
Hello all,

I'm facing an mysterious error while trying to deploy a basic grid5000 environment using this plugin
![image](https://user-images.githubusercontent.com/20845649/122976767-06a50d00-d395-11eb-963f-fc3af2451be4.png)

I'm working on the **Grenoble** site of grid5k

Any ideas ?

**Comment by pmorillon** [comment]
Hello, it's a normal behavior when no compute nodes are available within 5 minutes (by default).
You can modify this default value, but in any case, you will have to wait for the availability of the nodes : https://registry.terraform.io/providers/pmorillon/grid5000/latest/docs/resources/grid5000_job#scheduled_at_limit

See Grid'5000 [status](https://www.grid5000.fr/w/Status) page to checks available nodes on each sites.

**Comment by Nivekiba** [comment]
Ok cool 
Thanks
