### ISSUE TITLE
Use an already deploy oarsub

### ISSUE THREAD

**Issue by Nivekiba** [pmorillon/terraform-provider-grid5000#17]
Hello,

Is there a way to use an already deploy oarsub (through his id) when using the terraform-provider-gri5000 plugin ?

**Comment by pmorillon** [comment]
https://registry.terraform.io/providers/pmorillon/grid5000/latest/docs/resources/grid5000_job#import

**Comment by Nivekiba** [comment]
Ok
Can i test it before closing the issue ? i just want to be sure it works well

**Comment by pmorillon** [comment]
sure

**Comment by Nivekiba** [comment]
Is it also possible to import "grid5000_deployment" resource ?

**Comment by pmorillon** [comment]
> Is it also possible to import "grid5000_deployment" resource ?

I do not understand why you need to do that ? a deployment is a one shot resource. Can you explain what do you need to do ?

**Comment by Nivekiba** [comment]
in case i already reserve nodes with oarsub and already deploy an environment (debian for example) on a specific partition, if i want to use that already deployed nodes, i need a "grid5000_deployment" within my terraform script

**Comment by pmorillon** [comment]
if you deploy an environment manually with kadeploy command, you do not need to declare it into the terraform manifest, just need a `grid5000_job` resource to get reserved node list and interact with them.
