### ISSUE TITLE
Deployment of custom environment fails

### ISSUE THREAD

**Issue by Kr0kspluish** [pmorillon/terraform-provider-grid5000#21]
Hi, 
I'm trying to deploy using terraform a custom environment I just created and it fails. 
Of course, I tried to deploy manually the environment and it works fine.
When I'm trying to deploy it with terraform, the deployment phase never ends (I waited up to almost 20 minutes), and with `TF_LOG=DEBUG` I only get the following error: 

    2022-06-26T22:21:09.141+0200 [DEBUG] provider.terraform-provider-grid5000_v0.0.8: 2022/06/26 22:21:09 Deployment #D-e82104e7-fdfe-499a-9f6e-e68454f70c82@nancy state is error

I added the environment to the kaenv3 registry, and deploying it manually using its name worked. With terraform, I tried:

    resource "grid5000_deployment" "deployment" {
        environment = "my_custom_env"
        key = file(var.g5k_keys.public)
        site = grid5000_job.job.site
        nodes = grid5000_job.job.assigned_nodes
    }

My whole terraform worked when replacing the environment with one of the Grid5000 standard ones.

I also tried to put my environment in the public folder of my home and used 

    resource "grid5000_deployment" "deployment" {
        environment = "http://public.nancy.grid5000.fr/~thdubuc/my_custom_img.tar.zst"
        key = file(var.g5k_keys.public)
        site = grid5000_job.job.site
        nodes = grid5000_job.job.assigned_nodes
    }

And that time I got the following error: 

    Error: POST https://api.grid5000.fr/stable/grid5000/sites/nancy/deployments: 502 <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    │ <html><head>
    │ <title>502 Proxy Error</title>
    │ </head><body>
    │ <h1>Proxy Error</h1>
    │ <p>The proxy server received an invalid
    │ response from an upstream server.<br />
    │ The proxy server could not handle the request<p>Reason: <strong>Error reading from remote server</strong></p></p>
    │ <hr>
    │ <address>Apache/2.4.38 (Debian) Server at <a href="mailto:support-staff@lists.grid5000.fr">api-server-v3.nancy.grid5000.fr</a> Port 4444</address>
    │ </body></html>
    │ 
    │ 
    │   with grid5000_deployment.deployment,
    │   on main.tf line 17, in resource "grid5000_deployment" "deployment":
    │   17: resource "grid5000_deployment" "deployment" {

Is there something I'm doing wrong, or is it impossible to deploy a custom environment on Grid5000 using this terraform plugin?

**Comment by pmorillon** [comment]
Hello,

I will try to reproduce.
Your custom environment `my_custom_env` is registered at Nancy ? the visibility of the environment is `shared` ?

**Comment by Kr0kspluish** [comment]
Thanks! Yes it is in Nancy. It is currently `private` but I can share it if you need.

**Comment by pmorillon** [comment]
> Thanks! Yes it is in Nancy. It is currently `private` but I can share it if you need.

Yes please

**Comment by Kr0kspluish** [comment]
It is now shared. I named it `ubuntu2204-min-5.15-nfs` for `kaenv3`, the description file is `env_5_15_nfs.yaml` and the tarball is `g5kimage-5_15_nfs.tar.zst`.

**Comment by pmorillon** [comment]
i have duplicated your environment into my namespace.
The deployment can not start, here the logs on the kadeploy server :

```
Internal Server Error  Invalid client's export -- There is no way to retrieve /home/thdubuc/public/g5kimage-5_15_nfs.tar.zst from the Kadeploy server. Consider using a server:// or a http:// URL
```

I need to update the provider to catch this error.

I have updated the registred environment with : 

```yaml
image:
  file: http://public.nancy.grid5000.fr/~thdubuc/g5kimage-5_15_nfs.tar.zst
  kind: tar
  compression: zstd
```

And it's works.

```tf
resource "grid5000_deployment" "debug" {
  site        = "nancy"
  environment = "ubuntu2204-min-5.15-nfs"
  nodes       = grid5000_job.debug.assigned_nodes
  key         = file("~/.ssh/id_ecdsa.pub")
}
```

```
❯ terraform state show grid5000_deployment.debug          
# grid5000_deployment.debug:
resource "grid5000_deployment" "debug" {
    environment = "ubuntu2204-min-5.15-nfs"
    id          = "D-c1cbf885-41ed-4987-8ccc-89c409e7560b"
    key         = <<-EOT
        ecdsa-sha2-nistp256 xxxx
    EOT
    nodes       = [
        "grisou-15.nancy.grid5000.fr",
    ]
    site        = "nancy"
    state       = "terminated"
}
```

**Comment by Kr0kspluish** [comment]
I just tested with your fix and it works well. Thanks a lot!
