### ISSUE TITLE
Remote deployment is it possible ?

### ISSUE THREAD

**Issue by Nivekiba** [pmorillon/terraform-provider-grid5000#3]
![image](https://user-images.githubusercontent.com/20845649/91199075-48bddd80-e6f5-11ea-9f41-b273f01b5f52.png)

I'm getting this error due to remoteness... My question is then if it is possible to deploy the kubernetes cluster and rke using terraform remotely.

If yes, what is the meaning of this error ?

**Comment by pmorillon** [comment]
It's not an issue about this provider. 
I can help you to deploy Kubernetes on Grid'5000, but it's not the good place.

Just to help : https://registry.terraform.io/providers/rancher/rke/latest/docs/resources/cluster#bastion_host

After that, you will be blocked with kubernetes provider, and you will need to use an ssh tunnel and configure the kubernetes provider like that : 

```tf
resource "null_resource" "ssh_tunnel" {
  depends_on = [rke_cluster.cluster]

  provisioner "local-exec" {
    command = "screen -S terraform_tunnel -d -m ssh -N -L 16443:${sort(grid5000_deployment.kubernetes.nodes)[0]}:6443 ${local.username}@${local.bastion_host} && sleep 5"
  }
}

provider "kubernetes" {
  load_config_file        = false
  host                    = "https://localhost:16443"
  username                = rke_cluster.cluster.kube_admin_user

  client_certificate      = rke_cluster.cluster.client_cert
  client_key              = rke_cluster.cluster.client_key
  cluster_ca_certificate  = rke_cluster.cluster.ca_crt
}
```

To start, maybe try to deploy from a Grid'5000 frontend like this : https://github.com/pmorillon/terraform-provider-grid5000/tree/master/examples/kubernetes

**Comment by Nivekiba** [comment]
Oh ok i see, i wil try it

and i already try to deploy from a g5k frontend. It works... but it's painful to modify and write my terraform files through ssh.

**Comment by pmorillon** [comment]
I agree, i prefer also work with terraform from my laptop, you have to think about the benefit / difficulty ratio in relation to what you want to do.

A good alternative : 
* Editor : https://code.visualstudio.com/docs/remote/ssh
* Terraform, Kubectl, Helm, k9s... installation on a Grid'5000 frontend : https://asdf-vm.com

**Comment by Nivekiba** [comment]
Ok i see , thanks a lot i will try it

**Comment by Nivekiba** [comment]
Unfortunately, the alternative with remote-ssh of visual studio doesn't work because the "remote-ssh" plugin required to create a directory and don't have enough permission to do that.

For the moment, i'm working through ssh command line and i hope i will find another solution

**Comment by Nivekiba** [comment]
A last one for the road please. How is it possible to specify the cluster type using terrform provider for grid5000 ?

**Comment by pmorillon** [comment]
You can use the OAR resources query format : 

```tf
resource "grid5000_job" "my_job" {
  name      = "terraform"
  site      = "rennes"
  command   = "sleep 1h"
  resources = "{cluster='parasilo'}/nodes=2"
  types     = ["deploy"]
}
```

**Comment by Nivekiba** [comment]
Ok thanks.
