### ISSUE TITLE
Add partition_number parameter for grid5000_deployment resource

### ISSUE THREAD

**Issue by pmorillon** [pmorillon/terraform-provider-grid5000#7]
And it is possible to change the default partition where the OS is installed ?

in command line we use **-p** option of the **kadeploy3*
in terraform plugin of grid5k is there an attribute ?

_Originally posted by @Nivekiba in https://github.com/pmorillon/terraform-provider-grid5000/issues/6#issuecomment-701290746_

**Comment by pmorillon** [comment]
Working on it.
But a bug into the Grid'5000 API blocks this feature. An issue have been submitted.

**Comment by pmorillon** [comment]
@Nivekiba, while Grid'5000 API is not fixed by the Grid5000 dev team, maybe we can try a workaround for your use case.

Do you need to deploy on /dev/sda5 in order to have more space for your docker containers ?

**Comment by pmorillon** [comment]
Ok, a temporary workaround could be into the docker installation script, before docker install command, as /dev/sda5 is mounted on /tmp : 

```sh
mkdir /tmp/docker && mkdir /var/lib/docker && mount --bind /tmp/docker /var/lib/docker
```

**Comment by Nivekiba** [comment]
Ok thanks.. it works

**Comment by pmorillon** [comment]
Will be released even if Grid5000 do not allow that through the API for now.
